# Generated by Django 5.1 on 2024-08-07 21:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('courts', models.IntegerField(default=0, verbose_name='Кол-во кортов')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата проведения')),
                ('comands_quantity', models.IntegerField(default=0, verbose_name='Кол-во команд')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Смешанный')], max_length=1, verbose_name='Пол')),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Взнос')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Призовой фонд')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.IntegerField(default=0, verbose_name='№ корта')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость')),
                ('price_weekday1', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена. Будни-день')),
                ('price_weekday2', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена. Будни-вечер')),
                ('price_weekend', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена. Выходной')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courts.location', verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Корт',
                'verbose_name_plural': 'Корты',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courts.location', verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
