# Generated by Django 5.1 on 2024-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_location_photo_reserve_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
