# Generated by Django 5.1 on 2024-09-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_alter_reserve_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
    ]
